FROM locustio/locust:2.20.0

# Copiar o locustfile
COPY locustfile.py /mnt/locust/locustfile.py

# Definir diretório de trabalho
WORKDIR /mnt/locust

# Expor porta da UI do Locust
EXPOSE 8089

# O comando será definido no docker-compose


